import XCTest
import AppKit
@testable import NotepadXXUI
@testable import NotepadXXEditor
@testable import NotepadXXCore

/// Timers and event monitors outlive the objects that made them unless someone
/// tears them down: the run loop retains a repeating timer, and an event
/// monitor belongs to the application, not the window that installed it.
@MainActor
final class ResourceLifetimeTests: XCTestCase {
    /// A caret timer must not be scheduled for an editor with no window; it
    /// would keep firing ten times a second for the life of the process.
    func testNoCaretTimerWithoutAWindow() {
        let controller = EditorViewController()
        controller.view.frame = NSRect(x: 0, y: 0, width: 400, height: 300)
        controller.load(text: "text")
        controller.caretBlinks = false          // this is what arms the timer

        XCTAssertFalse(controller.hasCaretTimer,
                       "a timer was scheduled for an editor that is not on screen")
    }

    /// And one that was running stops when the editor leaves the screen.
    func testTheCaretTimerStopsWhenTheEditorDisappears() {
        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 400, height: 300),
                              styleMask: [.titled], backing: .buffered, defer: false)
        let controller = EditorViewController()
        window.contentView = controller.view
        controller.load(text: "text")
        controller.viewDidAppear()
        controller.caretBlinks = false
        XCTAssertTrue(controller.hasCaretTimer, "on screen with blinking off, it should be armed")

        controller.viewDidDisappear()
        XCTAssertFalse(controller.hasCaretTimer, "the timer outlived the editor being shown")
    }

    /// The window removes its application-wide monitors when it closes.
    func testClosingTheWindowRemovesItsEventMonitors() throws {
        let controller = MainWindowController()
        controller.adopt(documents: [TextDocument(text: "x")], activeIndex: 0)
        controller.window?.contentView?.layoutSubtreeIfNeeded()
        controller.selectAllOccurrencesAction(nil)   // installs the multi-caret monitor

        XCTAssertNotNil(controller.documentSwitcherMonitor, "the switcher monitor was installed")

        let window = try XCTUnwrap(controller.window)
        controller.windowWillClose(Notification(name: NSWindow.willCloseNotification, object: window))

        XCTAssertNil(controller.documentSwitcherMonitor, "switcher monitor still installed")
        XCTAssertNil(controller.multiCaretMonitor, "multi-caret monitor still installed")
    }

    /// An editor must actually deallocate once nothing holds it.
    func testAnEditorDeallocates() {
        weak var weakEditor: EditorViewController?
        autoreleasepool {
            let controller = EditorViewController()
            controller.view.frame = NSRect(x: 0, y: 0, width: 400, height: 300)
            controller.load(text: "text")
            weakEditor = controller
        }
        XCTAssertNil(weakEditor, "the editor is still alive; something retains it")
    }
}

/// Clipboard history reads whatever the user copies anywhere on the system, so
/// what it declines to record matters as much as what it keeps.
@MainActor
final class ClipboardPrivacyTests: XCTestCase {
    private func pasteboard() -> NSPasteboard {
        let board = NSPasteboard(name: NSPasteboard.Name("NotepadXXTest.\(UUID().uuidString)"))
        board.clearContents()
        return board
    }

    /// A password manager marks its pasteboard concealed to ask not to be
    /// recorded. Honouring that is the difference between a clipboard history
    /// and a password logger.
    func testConcealedClipboardsAreNotRecorded() {
        let board = pasteboard()
        board.declareTypes([NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
                            .string], owner: nil)
        board.setString("correct horse battery staple", forType: .string)

        XCTAssertFalse(ClipboardHistoryPanel.mayRecord(board),
                       "a concealed clipboard was recorded; this is how passwords leak")
    }

    func testTransientAndAutoGeneratedClipboardsAreNotRecorded() {
        for marker in ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            let board = pasteboard()
            board.declareTypes([NSPasteboard.PasteboardType(marker), .string], owner: nil)
            board.setString("scratch", forType: .string)
            XCTAssertFalse(ClipboardHistoryPanel.mayRecord(board), "\(marker) was recorded")
        }
    }

    /// An ordinary copy is still kept, or the feature does nothing.
    func testOrdinaryClipboardsAreStillRecorded() {
        let board = pasteboard()
        board.declareTypes([.string], owner: nil)
        board.setString("some text the user copied", forType: .string)

        XCTAssertTrue(ClipboardHistoryPanel.mayRecord(board))
    }

    /// The pasteboard poll stops when the window that owns the panel closes.
    func testClosingTheWindowStopsThePasteboardPoll() throws {
        let controller = MainWindowController()
        controller.adopt(documents: [TextDocument(text: "x")], activeIndex: 0)
        controller.window?.contentView?.layoutSubtreeIfNeeded()

        let panel = try XCTUnwrap(controller.clipboardHistoryPanel,
                                  "the window should hold the clipboard panel")
        XCTAssertTrue(panel.isPolling, "it polls while the window is open")

        let window = try XCTUnwrap(controller.window)
        controller.windowWillClose(Notification(name: NSWindow.willCloseNotification, object: window))

        XCTAssertFalse(panel.isPolling, "the poll outlived the window")
    }
}
